
package modeloqytetet;

/**
 *
 * @author migue
 */
public enum EstadoJuego {
    JA_CONSORPRESA, ALGUNJUGADORENBANCARROTA, JA_PUEDECOMPRAROGESTIONAR, JA_PUEDEGESTIONAR, JA_PREPARADO, JA_ENCARCELADO, JA_ENCARCELADOCONOPCIONDELIBERTAD
}
